pipeline {
	agent { node { label 'maven' } }
	environment { APP_NAMESPACE = 'hgsdlb-recover' }
	stages {
		stage('Test') {
			steps {
				dir('shopping-cart-v2') {
					sh './mvnw clean test'
				}
			}
		}
	}
}
